# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shortname',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
