# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-24 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_auto_20170218_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashentry',
            options={'default_permissions': (), 'get_latest_by': 'created_date', 'ordering': ('created_date',), 'verbose_name_plural': 'Cash entries'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_permissions': (), 'ordering': ['statement', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
